<?php if(!defined('APPLICATION')) die();
// DO NOT EDIT THIS FILE
// All of the settings defined here can be overridden in the /conf/config.php file.

$Configuration['Faq']['Questions']['PerPage'] = False;
$Configuration['Faq']['Questions']['OnlyCategory'] = False;
$Configuration['Faq']['Candy']['SectionID'] = False;

